title: Nico Schuster # your name (or website title) here
logo: "/images/Headshot_2018.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-schuster-/">LinkedIn</a> 
  <br>
  <a href="pdf/Resume_NicholasSchuster.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">GitHub</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Twitter</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Youtube</a> 
  
theme: jekyll-theme-minimal
