title: Nico Schuster | Professional Profile
description: >
  Industrial Engineering & Operations Research | Business Analytics & Finance
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-schuster-/">LinkedIn</a> | 
  <a href="pdf/Resume_NicholasSchuster.pdf">Resume</a> | 
  <a href="https://github.com/nicoschuster01/">GitHub</a>

theme: jekyll-theme-cayman
